openapi: 3.0.0
servers:
  - url: 'https://get-accept-dev.offisante.fr/'
  - url: 'https://get-accept.offisante.fr'
info:
  version: 1.0.0
  title: OffiSanté ESignature API
  description: OffiSanté Electronic Signature API Documentation
  contact:
    name: API Support
    email: backoffice@offisante.fr
    url: https://offisante.fr
tags:
  - name: Authentication
  - name: Documents

paths:
  /api/auth:
    post:
      tags:
        - Authentication
      summary: API Authentication
      description: Authenticate to the API
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: username
                password:
                  type: string
                  example: p@ssw0rd
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidTokenResponse"
        401:
          description: Invalid login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidTokenResponse"
        500:
          description: Internal server error

  /api/1/documents:
    post:
      tags:
        - Documents
      summary: Create a document for signature
      description: Create a document for signature, create a salesforce registration case and return the document informations
      operationId: createDocument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: john.doe@example.com
                  description: Email of the signer
                first_name:
                  type: string
                  example: John
                  description: First name of the signer
                last_name:
                  type: string
                  example: Doe
                  description: Last name of the signer
                phone:
                  type: string
                  example: 0601020304
                  description: Phone number of the signer
                pharmacy_name:
                  type: string
                  example: Pharmacie de la paix
                  description: Name of the pharmacy for pharmacy templates
                adress:
                  type: string
                  example: 1 rue de la paix
                  description: Adress of the pharmacy for pharmacy templates
                finess:
                  type: string
                  example: 123456789
                  description: FINESS number of the pharmacy for pharmacy templates
                social_form:
                  type: string
                  example: SELARL
                  description: Social form of the pharmacy for pharmacy templates
                rcs:
                  type: string
                  example: 123456789
                  description: RCS number of the pharmacy for pharmacy templates
                cip:
                  type: string
                  example: 1234567
                  description: CIP of the pharmacy for pharmacy templates
                siret:
                  type: string
                  example: 123456789
                  description: SIRET number of the pharmacy for pharmacy templates
                lgo:
                  type: string
                  example: LGPI
                  description: LGO of the pharmacy (LGPI, WINPHARMA, LEO, etc) for pharmacy templates
                typology:
                  type: string
                  example: rurale
                  description: Typology of the pharmacy (rurale, centre ville, zone commerciale, etc) for pharmacy templates
                group:
                  type: string
                  example: Giphar
                  description: Groupement of the pharmacy for pharmacy templates
                rpps:
                  type: string
                  example: 123456789
                  description: RPPS number of the pharmacy for medecin templates
              required:
                - email
                - first_name
                - last_name
                - phone


      responses:
        200:
          description: Client already signed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponse"
        201:
          description: Document created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponse"
        401:
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidTokenResponse"
        422:
          description: Unprocessable Entity
        500:
          description: Internal server error
      security:
        - access_auth:
            []
  /api/1/documents/{id}/status:
    get:
      tags:
        - Documents
      summary: Get the status of a document
      description: Get the status of a document
      operationId: getDocumentStatus
      parameters:
        - in: path
          name: id
          required: true
          description: Document ID
          schema:
            type: string
      responses:
        200:
          description: Document status response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentStatusResponse"
        401:
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidTokenResponse"
        404:
          description: Document not found
        500:
          description: Internal server error
      security:
        - access_auth:
            []
components:
  securitySchemes:
    access_auth:
      type: apiKey
      in: header
      name: x-access-token
  schemas :

    ValidTokenResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQsdf

    InvalidTokenResponse :
      type: object
      description: Invalid token
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Failed to authenticate token.

    DocumentResponse:
      description: Document response
      type: object
      properties:
        id:
          type: string
          example: 5f5e3e3edsd
          description: Document ID
        document_url:
          type: string
          example: https://offisante-api.getaccept.com/v/1732b5b05beee-3e3e-3e3e-3e3e-3e3e3e3e3e3e
          description: URL to sign the document
        message:
          type: string
          example: Document created for signature and Salesforce registration case created.

    DocumentStatusResponse:
      description: Document status
      type: object
      properties:
        status:
          type: string
          example: signed
          description : |
            Document status.
            Possible values: 
              - 'sealed' :  Document created and not viewed yet by the signer
              - 'viewed' :  Document viewed by the signer
              - 'reviewed' :  Document entirely reviewed by the signer
              - 'signed' :  Document signed by the signer
              - 'rejected' :  Document rejected by the signer